/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\monster.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/monster.glb')
  const { actions,names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].play()
  }, [])
  

  return (
    <group ref={group} {...props} dispose={null} scale={8}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01} position={[0,-0.2,0]}>
          <primitive object={nodes.mixamorigHips} />
          <group name="parasiteZombie">
            <skinnedMesh name="parasiteZombie_1" geometry={nodes.parasiteZombie_1.geometry} material={materials.parasitezombie_Material1} skeleton={nodes.parasiteZombie_1.skeleton} castShadow />
            <skinnedMesh name="parasiteZombie_2" geometry={nodes.parasiteZombie_2.geometry} material={materials.parasitezombie_Material} skeleton={nodes.parasiteZombie_2.skeleton} castShadow />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/monster.glb')
